# Site settings
title: GRAYSCALE
email: grayscale@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musician
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SBootstrap
github_username:  IronSummitMedia/startbootstrap
googleplus_username: Startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
