# Site settings
title: Gian Solo 
email: soundsbygian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musician, Producer & Writer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gian_solo
github_username:  
googleplus_username: 

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
